name: flutter_riverpod_todo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flex_color_scheme: ^7.2.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.3.6
  font_awesome_flutter: ^10.5.0
  gap: ^3.0.1
  go_router: ^10.0.0
  google_fonts: ^5.1.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.1
  path: ^1.8.3
  sqflite: ^2.3.0
  flutter_i18n: ^0.34.0
  i18n_extension: ^4.1.0
  cached_network_image: 3.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true

  uses-material-design: true

assets: